src/Entity/Asset.php
<?php

namespace App\Entity;

use App\Repository\AssetRepository;
use App\Service\FileUploader;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=AssetRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Asset
{
    public const ALLOWED_TYPES = [
        'image' => 0,
        'document' => 1,
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("media_collection")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("media_collection")
     */
    private $path;

    /**
     * @ORM\Column(type="smallint")
     * @Groups("media_collection")
     */
    private $type;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @Groups("media_collection")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="assets")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("media_collection")
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups("media_collection")
     */
    private $caption;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=CroppedAsset::class, mappedBy="asset", orphanRemoval=true)
     */
    private $croppedAssets;

    /**
     * @ORM\OneToMany(targetEntity=PageAsset::class, mappedBy="asset", orphanRemoval=true)
     */
    private $pageAssets;

    public function __construct()
    {
        $this->croppedAssets = new ArrayCollection();
        $this->pageAssets = new ArrayCollection();
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCaption(): ?string
    {
        return $this->caption;
    }

    public function setCaption(?string $caption): self
    {
        $this->caption = $caption;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function setCreatedAtValue(): void
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->updatedAt = new \DateTime();
    }

    /**
     * @return Collection|CroppedAsset[]
     */
    public function getCroppedAssets(): Collection
    {
        return $this->croppedAssets;
    }

    public function addCroppedAsset(CroppedAsset $croppedAsset): self
    {
        if (!$this->croppedAssets->contains($croppedAsset)) {
            $this->croppedAssets[] = $croppedAsset;
            $croppedAsset->setAsset($this);
        }

        return $this;
    }

    public function removeCroppedAsset(CroppedAsset $croppedAsset): self
    {
        if ($this->croppedAssets->removeElement($croppedAsset)) {
            // set the owning side to null (unless already changed)
            if ($croppedAsset->getAsset() === $this) {
                $croppedAsset->setAsset(null);
            }
        }

        return $this;
    }

    /**
     * @Groups("media_collection")
     */
    public function getPublicPath(): string
    {
        return FileUploader::ASSET_PATH . $this->getPath();
    }

    /**
     * @return Collection|PageAsset[]
     */
    public function getPageAssets(): Collection
    {
        return $this->pageAssets;
    }

    public function addPageAsset(PageAsset $pageAsset): self
    {
        if (!$this->pageAssets->contains($pageAsset)) {
            $this->pageAssets[] = $pageAsset;
            $pageAsset->setAsset($this);
        }

        return $this;
    }

    public function removePageAsset(PageAsset $pageAsset): self
    {
        if ($this->pageAssets->removeElement($pageAsset)) {
            // set the owning side to null (unless already changed)
            if ($pageAsset->getAsset() === $this) {
                $pageAsset->setAsset(null);
            }
        }

        return $this;
    }
}

templates/page/blocks/_header.html.twig
<h{{ level }} class="subtitle is-{{ level }}">
    {{ content }}
</h{{ level }}>

templates/page/blocks/_image.html.twig
<div class="modal-wrapper" data-controller="common--modal">
    <figure class="figure">
        <img
            src="{{ asset.publicPath ?? asset.path }}"
            data-action="click->common--modal#open">
        {% if caption %}
            <figcaption class="figcaption mt-2">
                {{ caption }}
            </figcaption>
        {% endif %}
    </figure>
    <div class="modal" data-common--modal-target="modal">
        <div class="modal-background" data-action="click->common--modal#close"></div>
        <div data-common--modal-target="modal">
            <div class="modal-content">
                <p class="image">
                    <img src="{{ asset.publicPath ?? asset.path }}">
                </p>
            </div>
        </div>
    </div>
</div>

templates/page/blocks/_image_grid.html.twig
<div class="image-grid-container mt-5 mb-5">
    <div class="columns is-multiline is-centered is-1">
        {% for image in images %}
            <div class="column is-{{ colWidth }}">
                <div class="image-grid-image-container">
                    <div class="image-grid-image-wrapper">
                        <div class="image-grid-image">
                            {{ include('page/blocks/_image.html.twig', {asset: image, caption: image.caption, isEmbed: true}) }}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

templates/page/blocks/_image_wrap.html.twig
<div class='image-wrap block mt-5 mb-5'>
    <div class='columns'>
        <div class='column image-wrap-column {{ col1 }}'>
            {% if imageContent == 1 %}
                {{ include('page/blocks/_image.html.twig', {asset: image, caption: ''}) }}
            {% else %}
                <div class="wrap-content">
                    {{ content|nl2br }}
                </div>
            {% endif %}
        </div>
        <div class='column image-wrap-column {{ col2 }}'>
            {% if imageContent == 2 %}
                {{ include('page/blocks/_image.html.twig', {asset: image, caption: ''}) }}
            {% else %}
                <div class="wrap-content">
                    {{ content|nl2br }}
                </div>
            {% endif %}
        </div>
    </div>
</div>

templates/page/blocks/_list.html.twig
<div class="content">
    {% if isOrdered %}
        <ol class="list">
    {% else %}
        <ul class="list">
    {% endif %}
    {% for item in items %}
        <li class="list-item">
            {{ item }}
        </li>
    {% endfor %}
    {% if isOrdered %}
        </ol>
    {% else %}
        </ul>
    {% endif %}
</div>